//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace profilio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class datum
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<long> Mobile { get; set; }
        public string email { get; set; }
        public string subject { get; set; }
        public string massage { get; set; }
        public Nullable<System.DateTime> Crd { get; set; }
    }
}
